### ISSUE TITLE
[21.04] Feature Request: Intellihide Dock

### ISSUE THREAD

**Issue by nathanbibb** [pop-os/beta#140]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 Fresh Install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I like to have the dock on the left, but if, for example, I have a terminal on the left and gedit on the right, if I am focused on gedit the doc comes up and blocks the terminal that I might want to read.  I used Intellihide (with the option to dodge all windows) in dash to dock to address this.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by RedBearAK** [comment]
I saw someone, possibly a dev, on the Mattermost chat who was not able to replicate this, and I think I might know why. 

I think it's important to note that the dock reveals itself in this manner for those of us who **_aren't using tiling_**. Many of the devs and other Pop!_OS users might be oblivious to why this is a problem because they use the tiling windows feature, which should cause the dock to always hide (I think) when there are two side-by-side tiled windows on screen. 

Right now the dock is using "intelligent" hiding, but only gets out of the way of the active/focused window. So other windows that don't have focus can end up getting overlapped by the dock, which refuses to hide unless an "active" window is overlapping the dock area. This can be very frustrating, since the dock is just basically getting in the way of seeing some things in other unfocused windows. 

To make this kind of hiding feature work for all users, it needs to have three distinct modes: 

**Automatic** = dock always hides itself unless actively being revealed by mouse

**Intelligent hiding, active window only** = This is the only current hiding mode. Dock hides only when active window overlaps the dock area. 

**Intelligent hiding, all windows** = Dock should hide itself whenever ANY window starts to overlap the dock area, regardless of focus. This is most similar to the actual "automatic" mode, but still leaves the dock visible whenever there isn't a window close enough to the dock area to force it to hide. 

I don't really understand why anyone would want to use any mode except the true "automatic" hiding mode, but users deserve the same choices that other desktop environments, shell extensions like `Hide Top Bar` or `Dash to Dock`, and applications like Plank present to their users. They usually have all three of these options available.

**Comment by jacobgkau** [comment]
Related/duplicate: https://github.com/pop-os/gnome-shell-extension-ubuntu-dock/issues/8

**Comment by jacobgkau** [comment]
The intellihide mode was changed to avoid all windows (not just focused windows) before release. (The "only focused windows" mode has limited use and is also a little buggy, with some apps counting all of their windows as focused and others only counting one of their windows at a time as focused.)
