### ISSUE TITLE
tensorflow-cuda-latest does not install everything that's needed

### ISSUE THREAD

**Issue by atharvalele** [pop-os/beta#17]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Fresh installed 19.10 and then updated from that.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

tensorflow-cuda-latest:
  Installed: 2.0~20.04
  Candidate: 2.0~20.04
  Version table:
 *** 2.0~20.04 500
        500 http://apt.pop-os.org/proprietary focal/main all Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

installing the `tensorflow-cuda-latest` metapackage does not install the related CUDA libraries listed on https://support.system76.com/articles/install-tensorflow/ 

`/usr/lib/tensorflow` directory is missing as well.

Therefore python cannot find installed tensorflow files

**Steps to reproduce (if you know):**

run `$ sudo apt install tensorflow-cuda-latest`

**Expected behavior:**

All libraries should be installed correctly

**Other Notes:**

MSI GL62M 7RDX
i5-7300HQ + GTX1050 - running in NVIDIA mode

**Comment by WatchMkr** [comment]
Starting with Pop 19.10, we built a new tool to manage Tensorflow containers called Tensorman. See the documentation here: https://support.system76.com/articles/use-tensorman/

Tensorman should get you up and running with any Tensorflow version you need to use.

If there's a case that doesn't work for you, file an issue against the repo so that we can improve the tool. https://github.com/pop-os/tensorman
