### ISSUE TITLE
Pop COSMIC extension's settings throw error

### ISSUE THREAD

**Issue by SirRFI** [pop-os/beta#267]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh install on VM.
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```sh
$ apt policy pop-cosmic 
pop-cosmic:
  Installed: 0.1.0~1631905924~21.10~df7e39a
  Candidate: 0.1.0~1634308107~21.10~ea74293
  Version table:
     0.1.0~1634308107~21.10~ea74293 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
 *** 0.1.0~1631905924~21.10~df7e39a 100
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
`Pop COSMIC` extension page has an error:
```
TypeError: box.add is not a function

Stack trace:
  buildPrefsWidget@/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/prefs.js:32:9
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
 ```
![pop-cosmic](https://user-images.githubusercontent.com/32642697/139556458-d594e13e-70b1-4cae-87b0-155270cc87df.png)

**Steps to reproduce (if you know):**
1. Open "Extensions" (`gnome-extensions-app`)
2. Find `Pop COSMIC` on the list and click gear icon to enter extension's settings
3. Window with error and stack trace will appear.

**Expected behavior:**
Open window with actual settings for the extensions, if any exists.

**Other Notes:**
None.

**Comment by jacobgkau** [comment]
Thank you for trying the beta. The `apt policy` output you provided indicates that there is an update available. The git commit log shows that the update was to fix this issue: https://github.com/pop-os/cosmic/commits/master_impish 

![image](https://user-images.githubusercontent.com/7199422/139696127-2b3d5752-7dbf-4659-8aeb-5d18e8ad6f31.png)

Can you please install all updates using `sudo apt update` and `sudo apt full-upgrade`, then reboot and confirm this issue is fixed?

**Comment by SirRFI** [comment]
I reinstalled the OS and updated it via installer and GUI on the same day, before reporting this. The commands you provided worked as expected - the error is no more:
![screenshot](https://user-images.githubusercontent.com/32642697/139734425-cd0f6da4-f74a-4f2e-a775-94ebfaebdd93.png)
This implies that some parts didn't update before though.

So, the issue is fixed, but not necessary the culprit behind it - feel free to close.

**Comment by jacobgkau** [comment]
If you only attempted to update through the GUI, you were likely affected by this issue: https://github.com/pop-os/beta/issues/269 

I'm going to close this issue since the problem being referred to here is resolved. Please watch the other issue for updates on the Pop!_Shop problem, and feel free to add any additional information there.
