### ISSUE TITLE
Screen brightness control not working on DELL XPS 15 

### ISSUE THREAD

**Issue by FrederikP** [pop-os/beta#33]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh install

**Issue/Bug Description:**
Screen brightness control doesn't have any effect on the actual screen brightness on my new DELL XPS 15 (UHD OLED model)

**Steps to reproduce (if you know):**

Fresh install of pop os 20.04, try to change screen brightness using buttons or the slider. Nothing happens with the screen brightness. Always full power it seems.

**Expected behavior:**

Screen brightness should adjust.

**Other Notes:**

- keyboard brightness setting works as expected

let me know what info I can supply to help with this
thanks

**Comment by rhb388** [comment]
you need to download an extension for OLED brightness on gnome...https://extensions.gnome.org/extension/1222/oled-dimmer/

**Comment by FrederikP** [comment]
Ah thanks.
I just found this info as well: https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019#screen-brightness-oled

But wouldn't it fit to the Pop!_OS philosophy to have that work without any additional steps?

Anyway, I'll try out the extenstion. Thanks for the suggestion

**Comment by rhb388** [comment]
That works as well.

It would be nice if Pop!_OS had OLED support out of the box.  I have the XPS 15 7590 and have tried almost every distro there is and none of them support OLED out of the box.

The gnome extension is the easiest method I've found that just simply works.

**Comment by leviport** [comment]
The OLED display in the System76 Adder WS is supported out of the box. There are current efforts to support other machines happening as well: https://github.com/pop-os/system76-oled/pull/5 , though it is a community effort at the moment since we don't have any Dells with OLED displays to test on. It looks like there is some difficulty detecting which models have OLED displays and which don't. Feel free to jump in and help out, even if it's just with testing!
