### ISSUE TITLE
Coming back from Fractional scaling, brings everything extremely small (also in ubuntu)

### ISSUE THREAD

**Issue by defecador** [pop-os/beta#35]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
No, running it from the USB iso
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Wrong resolution when deactivating fractional scaling

**Steps to reproduce (if you know):**

When you change the scale to 125% and then, deactivate the fractional scaling, it brings everything to a really really high resolution, like 0,25% or so. 

**Expected behavior:**

Be back to 100%.

**Other Notes:**

I have seen this issue also in Ubuntu 20.04 beta

**Comment by defecador** [comment]
> No, running it from the USB iso

from 19.10 using the Terminal doing an Upgrade

**Comment by leviport** [comment]
Can confirm. It only happens when I flip the fractional scaling switch off when a display is set to a fractional scale value (125%, 150%, etc).

**Comment by WatchMkr** [comment]
Notes from https://github.com/pop-os/beta/issues/67

https://github.com/pop-os/beta/issues/67

Selecting 125% zooms into a portion of the screen at a time which moves around when I mouse around the edges. Selecting 150% and the rest simply displays a black screen and returns back to previous setting after a while.

Other Notes:

I was previously using the x-11-randr-fractional-scaling setting for mutter in 19.10 without any issue.

I’m running the NVidia ISO with a 1080TI GPU on an Acer S277HK Monitor at 3840 x 2160 resolution on a freshly installed system and all updates installed.

**Comment by WatchMkr** [comment]
Fractional scaling was not in Pop!_OS 19.10. We'll remove Fractional Scaling from GNOME Displays until it's ready for release. Tracking here: https://github.com/pop-os/gnome-control-center/issues/89

**Comment by yunghoy** [comment]
Copied from https://github.com/pop-os/gnome-control-center/issues/89

I'm pretty sure this can be a good example why code quality of open source cannot be better than commercial programs. Someone can refer this example on their books.

My display setting is with 4k and 1.5 fractional scaling.

As of 08/29/2021, I found "full screen" mode game picks 6144 x 3456 resolution. Basically, this resolution cannot be lower than 6k. Since the game picks 6k resolution, it's extremely hard to play my game with RTX 2070. I remember that this bug was from 2018 (Ubuntu 18.04)

**Comment by leviport** [comment]
This should have been closed when https://github.com/pop-os/gnome-control-center/issues/89 was closed.
