### ISSUE TITLE
pop desktop wont upgrade. 

### ISSUE THREAD

**Issue by tuananh** [pop-os/beta#375]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 

upgrade from 21.10 to 22.04

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

The following packages have been kept back:
  pop-desktop

**Steps to reproduce (if you know):**

sudo apt update && sudo apt upgrade

**Expected behavior:**

pop-desktop to be upgraded.

**Other Notes:**

**Comment by tuananh** [comment]
looks like i have to manually remove `pulseaudio` and then it will work after.

**Comment by jacobgkau** [comment]
Thank you for the report. This was a known breaking change and a `sudo apt full-upgrade` (instead of regular `upgrade`) should have also resolved the issue. Did you initially upgrade to 22.04 before March 21st, when the [change](https://github.com/pop-os/desktop/pull/80) was [released](https://github.com/pop-os/repo-release/pull/54)?

**Comment by tuananh** [comment]
i tried full-upgrade and dist-upgrade but it didnt work.

i just upgraded to 22.04 today. prior that, i have 21.10 running with pipewire.
