### ISSUE TITLE
GNOME Screenshot package got uninstalled automatically

### ISSUE THREAD

**Issue by Booligoosh** [pop-os/beta#404]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 Upgrade from 21.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
At some point during the beta, the Screenshot app got uninstalled automatically. I can't test it, but this may mean it's not getting included in fresh installs either. My last screenshot is from 8 April, so must have been sometime around then when the package was removed. I was able to re-install GNOME Screenshot via the Pop!_Shop, the source is shown as `Ubuntu (deb)`.

**Steps to reproduce (if you know):**
Try taking a screenshot via keyboard shortcut, nothing happens. Searching for "screenshot" in the launcher does not bring up the Screenshot app.

**Expected behavior:**
The Screenshot app is automatically installed and doesn't get removed.

**Other Notes:**

**Comment by leviport** [comment]
Gnome has implemented a new screenshot UI, and it doesn't depend on the screenshot app anymore, so that removal was intentional. If you've set custom shortcuts related to the old screenshot app, they might need to be updated for the new screenshot UI. Here is what my settings look like, and they seem to work as expected:

![2022-04-18_10-25](https://user-images.githubusercontent.com/13512097/163839515-a0ac82a4-5ba1-4692-8164-119e7dd2f29f.png)

**Comment by Booligoosh** [comment]
Good to know, thanks. However, just letting you know that the new Screenshot app wasn't installed automatically (which I assume is expected behaviour), I had to install it myself from the Pop Shop!

**Comment by leviport** [comment]
Gotcha, that's expected then so I'll close this issue. Thanks for the report and for helping test the beta!
