### ISSUE TITLE
popos 20.04 amd intel not booting

### ISSUE THREAD

**Issue by geoubuntu** [pop-os/beta#41]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**fresh install

 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
created usb sticker with etcher. put the usb dongle in the pc.. I see pop os will boot in x seconds... then black screen of death. usb is not flashing anything. the notebook is a dell inspiron

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by WatchMkr** [comment]
Is the current 19.10 version able to boot and install?

**Comment by geoubuntu** [comment]
Yes!

Il giorno mer 22 apr 2020 alle 01:27 WatchMkr <notifications@github.com> ha
scritto:

**Comment by WatchMkr** [comment]
In that case, this is likely a bad ISO download or write to the usb drive. If you already have a Pop install, use the pre-installed USB Flasher instead of etcher. 

Try re-downloading and writing to a different usb drive. Perhaps talk to folks in Pop Chat that can help with those issues. Https:chat.pop-os.org.

**Comment by geoubuntu** [comment]
Downloaded the first time with the link in distrowatch and the second time
from github. Usb drive works right . Guess I ll wait the official release

Il giorno mer 22 apr 2020 alle 15:46 WatchMkr <notifications@github.com> ha
scritto:

**Comment by geoubuntu** [comment]
the problem was in a PTT security to set to off in bios in addiction to
disable securekey
