### ISSUE TITLE
Firefox Bug and Gedit

### ISSUE THREAD

**Issue by ThierryBP** [pop-os/beta#61]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

Fresh install 20.04

Issue 1- Cant dissable tittle bar in firefox.
Issue 2- Cant open gedit files in desktop, it only work if i open the gedit files in desktop from file manger

**Comment by matrix8967** [comment]
I had the same titlebar issue in Firefox when upgrading from 19.10 --> 20.04.

A work around is:

`sudo apt install appmenu-gtk2-module appmenu-gtk3-module`

`GTK_CSD=1 firefox`

I'm assuming you can edit firefox's desktop file, but I'm gonna wait to figure out the root cause before I do that.

I'm not experiencing the 2nd issue with `gedit`.

**Comment by Kartonrealista** [comment]
A way easier but probably more ghetto fix than what @matrix8967 suggested is to disable "Show window titles" in Pop shell, although that setting applies to all apps. I'll leave a screenshot showing the double bar (with two x's in the right corner) and the solution
![Screenshot from 2020-04-24 11-52-02](https://user-images.githubusercontent.com/63356574/80199834-0b035800-8622-11ea-8881-8fffdb5e32e8.png)
![Screenshot from 2020-04-24 11-46-51](https://user-images.githubusercontent.com/63356574/80199866-15255680-8622-11ea-8ba8-9c81135d553c.png)

**Comment by Kartonrealista** [comment]
Also this seems to be the same issue as #2

**Comment by brs17** [comment]
The Firefox issue seems to have been resolved as is mentioned in the issue @Kartonrealista pointed out. It also appears that the gedit issue has been resolved as well.
