### ISSUE TITLE
Question about updating to lts version

### ISSUE THREAD

**Issue by lzyang2000** [pop-os/beta#91]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 Upgraded from 19.10  

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pop-upgrade  

**Issue/Bug Description:**
I am wondering when the LTS version is released, will those of us who updated from 19.10/19.04 to 20.04 receive the LTS version or the non-LTS version?  
Thanks!  

**Steps to reproduce (if you know):**
None  

**Expected behavior:**
None  
 

**Other Notes:**
None

**Comment by Apogeum12** [comment]
In my opinion ubuntu 20.04 lts have to much bugs. Probably people from PopOs wait on upgrade from Canonical. I bet minimum 1 month to "lts" version PoP!_Os.

**Comment by madredhatter22** [comment]
There is only one version of 20.04 if that's what you're asking. It's just that it will have the longer support life since it's an LTS version so there is no distinction between upgrading from 18.04 versus from 19.10 into 20.04. Regardless of your upgrade path, you'll still be on the same 20.04 after the upgrade. It will be the choice of the users thereafter whether they want to stay on 20.04 to continue on the LTS path until 22.04 or if they'd rather continue upgrading to the interim releases (20.10, 21.04, etc.).

**Comment by lzyang2000** [comment]
Thanks, cuz today I heard from my friends that there are 2 flavors of 20.04 for some reason - I always thought that there is only one. Closing the issue.
